// GENERATED by `pnpm run build:engine` from packages/flight-sim/src — do not edit by hand.
// See scripts/build-engine.mjs and ADR-010.

// packages/flight-sim/src/constants.ts
var R_EARTH_KM = 6371.0088;
var BASE_SPEED_MPH = 110;
var BASE_SPEED_KMH = 177.02784;
var MIN_FLIGHT_MS = 9e4;
var MAX_FLIGHT_MS = 7 * 24 * 60 * 60 * 1e3;
var BASE_HAZARD_PER_KM = 2002e-9;
var MAX_DEATH_PROBABILITY = 0.08;
var MAX_WIND_COMPONENT_KMH = 25;
var SIM_VERSION = 1;
var DEFAULT_CONDITIONS = {
  windComponentKmh: 0,
  stormIntensity: 0,
  predatorPressure: 0
};

// packages/flight-sim/src/geo.ts
var rad = (d) => d * Math.PI / 180;
var deg = (r) => r * 180 / Math.PI;
function haversineKm(a, b) {
  const dLat = rad(b.lat - a.lat);
  const dLon = rad(b.lon - a.lon);
  const la1 = rad(a.lat);
  const la2 = rad(b.lat);
  const h = Math.sin(dLat / 2) ** 2 + Math.cos(la1) * Math.cos(la2) * Math.sin(dLon / 2) ** 2;
  return 2 * R_EARTH_KM * Math.asin(Math.min(1, Math.sqrt(h)));
}
function interpolate(a, b, f) {
  const t = f < 0 ? 0 : f > 1 ? 1 : f;
  const d = haversineKm(a, b) / R_EARTH_KM;
  if (d < 1e-12) return { lat: a.lat, lon: a.lon };
  const sinD = Math.sin(d);
  if (Math.abs(sinD) < 1e-12) {
    return { lat: a.lat + (b.lat - a.lat) * t, lon: a.lon + (b.lon - a.lon) * t };
  }
  const A = Math.sin((1 - t) * d) / sinD;
  const B = Math.sin(t * d) / sinD;
  const la1 = rad(a.lat);
  const lo1 = rad(a.lon);
  const la2 = rad(b.lat);
  const lo2 = rad(b.lon);
  const x = A * Math.cos(la1) * Math.cos(lo1) + B * Math.cos(la2) * Math.cos(lo2);
  const y = A * Math.cos(la1) * Math.sin(lo1) + B * Math.cos(la2) * Math.sin(lo2);
  const z = A * Math.sin(la1) + B * Math.sin(la2);
  return { lat: deg(Math.atan2(z, Math.hypot(x, y))), lon: deg(Math.atan2(y, x)) };
}
function bearingDeg(a, b) {
  const la1 = rad(a.lat);
  const la2 = rad(b.lat);
  const dLon = rad(b.lon - a.lon);
  const y = Math.sin(dLon) * Math.cos(la2);
  const x = Math.cos(la1) * Math.sin(la2) - Math.sin(la1) * Math.cos(la2) * Math.cos(dLon);
  return (deg(Math.atan2(y, x)) + 360) % 360;
}
function densify(a, b, steps) {
  const n = Math.max(1, Math.floor(steps));
  const out = [];
  for (let i = 0; i <= n; i++) out.push(interpolate(a, b, i / n));
  return out;
}
function splitAtAntimeridian(points) {
  if (points.length === 0) return [];
  const segments = [[points[0]]];
  for (let i = 1; i < points.length; i++) {
    const prev = points[i - 1];
    const curr = points[i];
    const jump = curr.lon - prev.lon;
    if (Math.abs(jump) > 180) {
      const sign = Math.sign(jump);
      const boundaryLon = -sign * 180;
      const unwrappedCurrLon = curr.lon - sign * 360;
      const denom = unwrappedCurrLon - prev.lon;
      const t = Math.abs(denom) > 1e-9 ? (boundaryLon - prev.lon) / denom : 0;
      const boundaryLat = prev.lat + t * (curr.lat - prev.lat);
      segments[segments.length - 1].push({ lat: boundaryLat, lon: boundaryLon });
      segments.push([{ lat: boundaryLat, lon: -boundaryLon }]);
    }
    segments[segments.length - 1].push(curr);
  }
  return segments.filter((s) => s.length > 1);
}
function recommendedSteps(a, b) {
  const angularDeg = haversineKm(a, b) / R_EARTH_KM * (180 / Math.PI);
  return Math.min(512, Math.max(24, Math.ceil(angularDeg / 2)));
}
function arcSegments(a, b, steps) {
  return splitAtAntimeridian(densify(a, b, steps ?? recommendedSteps(a, b)));
}

// packages/flight-sim/src/rng.ts
function mulberry32(seed) {
  let a = seed >>> 0;
  return function next() {
    a = a + 1831565813 | 0;
    let t = Math.imul(a ^ a >>> 15, 1 | a);
    t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}
function hashString(s) {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}
function streamFor(seed, ns) {
  return mulberry32((seed ^ hashString(ns)) >>> 0);
}

// packages/flight-sim/src/speed.ts
function clamp(v, lo, hi) {
  return v < lo ? lo : v > hi ? hi : v;
}
function effectiveSpeedKmh(i) {
  const storm = clamp(1 - 0.35 * clamp(i.stormIntensity, 0, 1), 0.5, 1);
  const fatigue = clamp(1 - 0.15 * (1 - Math.exp(-Math.max(0, i.distanceKm) / 5e3)), 0.7, 1);
  const wind = clamp(i.windComponentKmh, -MAX_WIND_COMPONENT_KMH, 0);
  return Math.max(20, BASE_SPEED_KMH * storm * fatigue + wind);
}
function durationMs(distanceKm, speedKmh) {
  const raw = Math.max(0, distanceKm) / Math.max(1, speedKmh) * 36e5;
  return clamp(raw, MIN_FLIGHT_MS, MAX_FLIGHT_MS);
}

// packages/flight-sim/src/hazard.ts
function deathProbability(i) {
  if (i.isFirstEverFlight) return 0;
  if (i.distanceKm <= 0) return 0;
  const lambda = BASE_HAZARD_PER_KM * (1 + 1.5 * clamp(i.stormIntensity, 0, 1)) * (1 + 1 * clamp(i.predatorPressure, 0, 1));
  return Math.min(MAX_DEATH_PROBABILITY, 1 - Math.exp(-lambda * i.distanceKm));
}
function sampleDeathFraction(rand) {
  const f = (rand() + rand()) / 2;
  return clamp(f, 0.02, 0.98);
}
function pickCause(rand, at, isOverWater) {
  const table = isOverWater ? [
    ["exhaustion", 0.5],
    ["lost_bearings", 0.35],
    ["storm", 0.15]
  ] : [
    ["hawk", 0.4],
    ["storm", 0.2],
    ["exhaustion", 0.15],
    ["window", 0.12],
    ["cat", 0.08],
    ["lost_bearings", 0.05]
  ];
  const polar = Math.abs(at.lat) > 60;
  const weights = table.map(
    ([cause, w]) => polar && cause === "hawk" ? [cause, w * 0.3] : [cause, w]
  );
  const total = weights.reduce((s, [, w]) => s + w, 0);
  let r = rand() * total;
  for (const [cause, w] of weights) {
    r -= w;
    if (r <= 0) return cause;
  }
  return weights[weights.length - 1]?.[0] ?? "exhaustion";
}

// packages/flight-sim/src/plan.ts
function planFlight(input) {
  const conditions = { ...DEFAULT_CONDITIONS, ...input.conditions };
  const distanceKm = haversineKm(input.origin, input.destination);
  const speedKmh = effectiveSpeedKmh({
    windComponentKmh: conditions.windComponentKmh,
    stormIntensity: conditions.stormIntensity,
    distanceKm
  });
  const totalMs = durationMs(distanceKm, speedKmh);
  const arrivesAtMs = input.departsAtMs + totalMs;
  const pub = {
    origin: input.origin,
    destination: input.destination,
    departsAtMs: input.departsAtMs,
    arrivesAtMs,
    distanceKm,
    initialBearingDeg: bearingDeg(input.origin, input.destination),
    effectiveSpeedKmh: speedKmh,
    simVersion: SIM_VERSION
  };
  const pDeath = deathProbability({
    distanceKm,
    stormIntensity: conditions.stormIntensity,
    predatorPressure: conditions.predatorPressure,
    isFirstEverFlight: input.isFirstEverFlight === true
  });
  const survives = streamFor(input.seed, "survival")() >= pDeath;
  if (survives) {
    return {
      pub,
      secret: {
        outcome: "delivered",
        deathAtMs: null,
        deathFraction: null,
        deathPoint: null,
        cause: null,
        resolveAtMs: arrivesAtMs
      }
    };
  }
  const fraction = sampleDeathFraction(streamFor(input.seed, "death"));
  const deathAtMs = input.departsAtMs + totalMs * fraction;
  const deathPoint = interpolate(input.origin, input.destination, fraction);
  const cause = pickCause(streamFor(input.seed, "cause"), deathPoint, false);
  return {
    pub,
    secret: {
      outcome: "died",
      deathAtMs,
      deathFraction: fraction,
      deathPoint,
      cause,
      resolveAtMs: deathAtMs
    }
  };
}

// packages/flight-sim/src/state.ts
function flightStateAt(f, nowMs) {
  const totalMs = f.arrivesAtMs - f.departsAtMs;
  if (nowMs <= f.departsAtMs) {
    return {
      phase: nowMs < f.departsAtMs ? "scheduled" : "in_flight",
      progress: 0,
      position: f.origin,
      headingDeg: f.initialBearingDeg,
      remainingMs: Math.max(0, f.arrivesAtMs - nowMs),
      remainingKm: f.distanceKm
    };
  }
  if (nowMs >= f.arrivesAtMs) {
    return {
      phase: "arrived",
      progress: 1,
      position: f.destination,
      headingDeg: bearingDeg(f.origin, f.destination),
      remainingMs: 0,
      remainingKm: 0
    };
  }
  const progress = totalMs <= 0 ? 1 : (nowMs - f.departsAtMs) / totalMs;
  const position = interpolate(f.origin, f.destination, progress);
  const ahead = interpolate(f.origin, f.destination, Math.min(1, progress + 1e-3));
  return {
    phase: "in_flight",
    progress,
    position,
    headingDeg: bearingDeg(position, ahead),
    remainingMs: f.arrivesAtMs - nowMs,
    remainingKm: f.distanceKm * (1 - progress)
  };
}
function lostStateAt(f, deathFraction) {
  const position = interpolate(f.origin, f.destination, deathFraction);
  const ahead = interpolate(f.origin, f.destination, Math.min(1, deathFraction + 1e-3));
  return {
    phase: "lost",
    progress: deathFraction,
    position,
    headingDeg: bearingDeg(position, ahead),
    remainingMs: 0,
    remainingKm: f.distanceKm * (1 - deathFraction)
  };
}

// packages/flight-sim/src/format.ts
var MINUTE = 6e4;
var HOUR = 60 * MINUTE;
var DAY = 24 * HOUR;
function formatEta(remainingMs) {
  if (remainingMs < MINUTE) return "arriving";
  if (remainingMs >= DAY) {
    const d = Math.floor(remainingMs / DAY);
    const h = Math.floor(remainingMs % DAY / HOUR);
    return h > 0 ? `${d}d ${h}h away` : `${d}d away`;
  }
  if (remainingMs >= HOUR) {
    const h = Math.floor(remainingMs / HOUR);
    const m = Math.floor(remainingMs % HOUR / MINUTE);
    return m > 0 ? `${h}h ${m}m away` : `${h}h away`;
  }
  return `${Math.floor(remainingMs / MINUTE)}m away`;
}
var KM_PER_MILE = 1.609344;
function withThousands(n) {
  return Math.round(n).toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
}
function formatDistance(km, unit) {
  return unit === "imperial" ? `${withThousands(km / KM_PER_MILE)} mi` : `${withThousands(km)} km`;
}
export {
  BASE_HAZARD_PER_KM,
  BASE_SPEED_KMH,
  BASE_SPEED_MPH,
  DEFAULT_CONDITIONS,
  MAX_DEATH_PROBABILITY,
  MAX_FLIGHT_MS,
  MAX_WIND_COMPONENT_KMH,
  MIN_FLIGHT_MS,
  R_EARTH_KM,
  SIM_VERSION,
  arcSegments,
  bearingDeg,
  clamp,
  deathProbability,
  densify,
  durationMs,
  effectiveSpeedKmh,
  flightStateAt,
  formatDistance,
  formatEta,
  hashString,
  haversineKm,
  interpolate,
  lostStateAt,
  mulberry32,
  pickCause,
  planFlight,
  recommendedSteps,
  sampleDeathFraction,
  splitAtAntimeridian,
  streamFor
};
