#!/usr/bin/env node
/**
 * `pnpm run build:engine` (M1-02).
 *
 * The Edge Function that releases a pigeon runs on Deno, which cannot resolve
 * a pnpm workspace package (`@pidge/flight-sim`) the way Node and Jest do.
 * Rather than maintain a second implementation of the flight physics, this
 * bundles the one real implementation to plain, dependency-free ESM that
 * Deno can import by a relative URL — see ADR-001 ("exactly one
 * implementation") and ADR-010 (this bundling decision).
 *
 * The output is committed. `supabase/functions/release-pigeon/index.ts`
 * imports it directly; nothing regenerates it at deploy time. CI regenerates
 * it and fails on `git diff`, so the committed file can never drift silently
 * from `packages/flight-sim/src`.
 */
import { build } from 'esbuild';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = join(dirname(fileURLToPath(import.meta.url)), '..');

export async function buildEngineBundle() {
  const result = await build({
    entryPoints: [join(rootDir, 'packages/flight-sim/src/index.ts')],
    outfile: join(rootDir, 'supabase/functions/_shared/flight-sim.js'),
    bundle: true,
    write: true,
    format: 'esm',
    platform: 'neutral',
    target: 'es2022',
    legalComments: 'none',
    banner: {
      js:
        '// GENERATED by `pnpm run build:engine` from packages/flight-sim/src — do not edit by hand.\n' +
        '// See scripts/build-engine.mjs and ADR-010.',
    },
  });
  return result;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await buildEngineBundle();
}
